name: Update Products

on:
  push:
    paths:
      - cattemp.xlsx

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install pandas openpyxl
      - name: Generate products.js
        run: python jscreate.py
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add products.js
          git commit -m "update: regenerate products.js" || echo "No changes"
          git push